tools/check-po: Check po files via msgfmt
This makes sure we don't end up with incorrect plural forms
or broken format strings.

Signed-off-by: Guido Günther <guido.gunther@puri.sm>

diff --git a/tools/check-po b/tools/check-po
--- a/tools/check-po
+++ b/tools/check-po
@@ -9,3 +9,13 @@ if intltool-update -m 2>&1 | grep -qs '/.*\.c'; then
   intltool-update -m
   exit 1
 fi
+
+# Check for broken po files
+for file in *.po; do
+  echo -n "Checking ${file}: "
+  msgfmt -v -c "${file}"
+  # Check for errors, msgfmt returns 0 on errors too
+  if msgfmt -c "${file}" 2>&1 | grep -qs 'fatal error'; then
+    exit 1
+  fi
+done
